spring.application.name=e-commerce

# Perfil activo: cambiá "h2" por "mysql" para usar phpMyAdmin
spring.profiles.active=h2

# JPA / Hibernate (Configuraciones comunes para ambas bases de datos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true